#!/bin/bash
# Quick Pusher Setup Script

echo "📡 Pusher Setup for BuddyScript Real-time Features"
echo "=================================================="
echo ""
echo "1. Go to: https://pusher.com/channels"
echo "2. Create account (free tier available)"
echo "3. Create new app with these settings:"
echo "   - Name: BuddyScript"
echo "   - Cluster: us2 (or closest to your users)"
echo "   - Frontend: React"
echo "   - Backend: Node.js"
echo ""
echo "4. Copy the following from your Pusher dashboard:"
echo "   - App ID"
echo "   - Key"  
echo "   - Secret"
echo "   - Cluster"
echo ""
echo "5. Add to Vercel environment variables:"
echo "   PUSHER_APP_ID=your-app-id"
echo "   PUSHER_KEY=your-key"
echo "   PUSHER_SECRET=your-secret"
echo "   PUSHER_CLUSTER=your-cluster"
echo "   NEXT_PUBLIC_PUSHER_KEY=your-key"
echo "   NEXT_PUBLIC_PUSHER_CLUSTER=your-cluster"
echo ""
echo "Free tier includes:"
echo "✅ 200,000 messages/day"
echo "✅ 100 concurrent connections"  
echo "✅ Unlimited channels"
echo ""
echo "This enables real-time notifications in your BuddyScript app! 🚀"